### ISSUE TITLE
 TS2304: Cannot find name 'MousetrapInstance'.

### ISSUE THREAD

**Issue by SaifAlDilaimi** [thm-projects/arsnova.click-v2#1]
Hello,

I have followed your installation guide here (https://github.com/thm-projects/arsnova.click-v2/blob/master/documentation/Frontend-Installationguide.md) but I'm stuck on the last step. I get following output:

```
> arsnova-click-v2-frontend@2.0.0 dev:ssr /net/vcac-ubuntu16/disc1/www/html/arsnova-clicks/arsnova-click-v2-frontend
> ng run frontend:serve-ssr

****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @ngx-translate/core : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @nguniversal/express-engine/tokens : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/platform-server : es2015 as esm2015
Compiling @nguniversal/common/engine : es2015 as esm2015
Compiling @ng-bootstrap/ng-bootstrap : es2015 as esm2015
Compiling angulartics2 : es2015 as esm2015
Compiling angular-svg-icon : es2015 as esm2015
Compiling angular2-hotkeys : es2015 as esm2015
Compiling @angular/service-worker : es2015 as esm2015
Compiling @auth0/angular-jwt : es2015 as esm2015
Compiling @stomp/ng2-stompjs : es2015 as esm2015
Compiling ng2-simple-mq : es2015 as esm2015
Compiling ngx-cookie-service : es2015 as esm2015
Compiling ngx-markdown : es2015 as esm2015
Compiling ngx-toastr : es2015 as esm2015
Compiling preboot : es2015 as esm2015
Compiling universal-cookie-consent : es2015 as esm2015
Compiling angulartics2/piwik : es2015 as esm2015
Compiling @fortawesome/angular-fontawesome : es2015 as esm2015
Compiling angular-tag-cloud-module : es2015 as esm2015
Compiling ngx-infinite-scroll : es2015 as esm2015
Compiling angular2-qrcode : main as umd
Compiling @ngx-translate/http-loader : es2015 as esm2015
Compiling ngx-translate-messageformat-compiler : es2015 as esm2015
Compiling @nguniversal/express-engine : es2015 as esm2015
⠋ Generating server application bundles...Compiling angular2-qrcode : module as esm5
✔ Server application bundle generation complete.

Initial Chunk Files | Names         |    Size
main.js             | main          | 4.13 kB

                    | Initial Total | 4.13 kB

Build at: 2020-12-07T12:41:30.862Z - Hash: d90cd36ec7520f8f842a - Time: 72343ms

Error: node_modules/angular2-hotkeys/lib/hotkeys.service.d.ts:10:16 - error TS2304: Cannot find name 'MousetrapInstance'.

10     mousetrap: MousetrapInstance;
                  ~~~~~~~~~~~~~~~~~



⠇ Generating server application bundles (phase: building)...
    Error: node_modules/angular2-hotkeys/lib/hotkeys.service.d.ts:10:16 - error TS2304: Cannot find name 'MousetrapInstance'.

    10     mousetrap: MousetrapInstance;
                      ~~~~~~~~~~~~~~~~~

✔ Browser application bundle generation complete.

Error: node_modules/angular2-hotkeys/lib/hotkeys.service.d.ts:10:16 - error TS2304: Cannot find name 'MousetrapInstance'.

10     mousetrap: MousetrapInstance;
                  ~~~~~~~~~~~~~~~~~



⠼ Generating server application bundles (phase: building)...this.debug is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! arsnova-click-v2-frontend@2.0.0 dev:ssr: `ng run frontend:serve-ssr`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the arsnova-click-v2-frontend@2.0.0 dev:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-07T12_42_13_736Z-debug.log

```

Is there anything I can do? I tried also the docker version but I cant access anything localhost:4200 neither 4210.

**Comment by PhilippSautner97** [comment]
Hello, 

this issue is known, we had a quick fix implemented in the code, but currently the quick fix doesnt work. 
There is a manual way to get by this problem, I will add this to the installation guide within the coming days so stay tuned!

**Comment by PhilippSautner97** [comment]
The fix is now added to the installationguide, have fun!

**Comment by SaifAlDilaimi** [comment]
awesome! I will test it monday!

**Comment by SaifAlDilaimi** [comment]
Hello Philipp,
so I have tried your fix but it seems that the frontend doesn't connect to the backend. I have started both (frontend & backend) on the same machine. Those are the currently running docker images:

```
root@vmits0454 ~ # docker ps
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                                             NAMES
2db8334cf794        arsnova/arsnova-click-backend:2.0.0-staging   "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes        0.0.0.0:3020->3010/tcp                                                                            arsnova-click-backend-staging
027069a9dff9        arsnova/arsnova-click-backend:2.0.0-beta      "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes        0.0.0.0:3030->3010/tcp                                                                            arsnova-click-backend-beta
2a37ea2d5c43        arsnova/arsnova-click-backend:2.0.0           "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes        0.0.0.0:3010->3010/tcp                                                                            arsnova-click-backend-master
a2723b45a3e3        mongo:4.0.5                                   "docker-entrypoint.s…"   7 days ago          Up 7 days           0.0.0.0:27017->27017/tcp                                                                          arsnova-click-backend-mongodb
8d7fc0f603b8        bitnami/rabbitmq:3.8.3                        "/opt/bitnami/script…"   7 days ago          Up 7 days           0.0.0.0:5672->5672/tcp, 0.0.0.0:15672->15672/tcp, 4369/tcp, 25672/tcp, 0.0.0.0:15674->15674/tcp   arsnova-click-backend-rabbitmq

```

So the backend logs this stuff 

```
arsnova-click-backend-master | (node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:15672
arsnova-click-backend-master |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
arsnova-click-backend-master | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 131)
arsnova-click-backend-staging | (node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:15672
arsnova-click-backend-staging |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
arsnova-click-backend-staging | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 131)
arsnova-click-backend-beta | (node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:15672
arsnova-click-backend-beta |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
arsnova-click-backend-beta | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 131)
arsnova-click-backend-master | (node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5672
arsnova-click-backend-master |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
arsnova-click-backend-master | From previous event:
arsnova-click-backend-master |     at Object.connect (/usr/src/app/node_modules/amqplib/channel_api.js:6:18)
arsnova-click-backend-master |     at AMQPConnector.<anonymous> (/usr/src/app/src/db/AMQPConnector.ts:35:30)
arsnova-click-backend-master |     at Generator.next (<anonymous>)
arsnova-click-backend-master |     at /usr/src/app/dist/db/AMQPConnector.js:8:71
arsnova-click-backend-master |     at new Promise (<anonymous>)
arsnova-click-backend-master |     at __awaiter (/usr/src/app/dist/db/AMQPConnector.js:4:12)
arsnova-click-backend-master |     at AMQPConnector.initConnection (/usr/src/app/dist/db/AMQPConnector.js:33:16)
arsnova-click-backend-master |     at MongoDbConnector.<anonymous> (/usr/src/app/src/db/MongoDBConnector.ts:63:28)
arsnova-click-backend-master |     at Generator.next (<anonymous>)
arsnova-click-backend-master |     at /usr/src/app/dist/db/MongoDBConnector.js:8:71
arsnova-click-backend-master |     at new Promise (<anonymous>)
arsnova-click-backend-master |     at __awaiter (/usr/src/app/dist/db/MongoDBConnector.js:4:12)
arsnova-click-backend-master |     at MongoDbConnector.initRabbitMQConnection (/usr/src/app/dist/db/MongoDBConnector.js:60:16)
arsnova-click-backend-master |     at MongoDbConnector.<anonymous> (/usr/src/app/src/db/MongoDBConnector.ts:50:14)
arsnova-click-backend-master |     at Generator.next (<anonymous>)
arsnova-click-backend-master |     at /usr/src/app/dist/db/MongoDBConnector.js:8:71
arsnova-click-backend-master |     at new Promise (<anonymous>)
arsnova-click-backend-master |     at __awaiter (/usr/src/app/dist/db/MongoDBConnector.js:4:12)
arsnova-click-backend-master |     at /usr/src/app/src/db/MongoDBConnector.ts:39:50
arsnova-click-backend-master |     at new Promise (<anonymous>)
arsnova-click-backend-master |     at MongoDbConnector.connect (/usr/src/app/src/db/MongoDBConnector.ts:39:12)
arsnova-click-backend-master |     at DbDAO.connectToDb (/usr/src/app/src/db/DbDAO.ts:38:29)
arsnova-click-backend-master |     at listOnTimeout (internal/timers.js:531:17)
arsnova-click-backend-master |     at processTimers (internal/timers.js:475:7)
arsnova-click-backend-master | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 132)
arsnova-click-backend-staging | (node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5672
arsnova-click-backend-staging |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
arsnova-click-backend-staging | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 132)
arsnova-click-backend-beta | (node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5672
arsnova-click-backend-beta |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
arsnova-click-backend-beta | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 132)
```

After fixing the error as you said the frontend has following logs:
```
root@vmits0454 /var/www/html/arsnova-clicks/arsnova-click-v2-frontend (staging *=) # npm run dev:ssr

> arsnova-click-v2-frontend@2.0.0 dev:ssr /net/vcac-ubuntu16/disc1/www/html/arsnova-clicks/arsnova-click-v2-frontend
> ng run frontend:serve-ssr

****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
✔ Server application bundle generation complete.

Initial Chunk Files                                                               | Names                                                                          |      Size
main.js                                                                           | main                                                                           |  11.49 MB

                                                                                  | Initial Total                                                                  |  11.49 MB

Lazy Chunk Files                                                                  | Names                                                                          |      Size
quiz-quiz-flow-quiz-flow-module.js                                                | quiz-quiz-flow-quiz-flow-module                                                | 518.63 kB
quiz-quiz-manager-quiz-manager-module.js                                          | quiz-quiz-manager-quiz-manager-module                                          | 502.78 kB
quiz-quiz-module.js                                                               | quiz-quiz-module                                                               | 167.06 kB
admin-admin-module.js                                                             | admin-admin-module                                                             | 122.42 kB
vendors~quiz-quiz-flow-quiz-flow-module.js                                        | vendors~quiz-quiz-flow-quiz-flow-module                                        |  82.65 kB
i18n-manager-i18n-manager-module.js                                               | i18n-manager-i18n-manager-module                                               |  64.00 kB
root-nickname-chooser-nickname-chooser-module.js                                  | root-nickname-chooser-nickname-chooser-module                                  |  52.62 kB
root-info-info-module.js                                                          | root-info-info-module                                                          |  36.30 kB
vendors~i18n-manager-i18n-manager-module~quiz-quiz-manager-quiz-manager-module.js | vendors~i18n-manager-i18n-manager-module~quiz-quiz-manager-quiz-manager-module |  27.83 kB

Build at: 2020-12-14T10:26:21.515Z - Hash: 194a69c832e9674a7b3c - Time: 119396ms
✔ Browser application bundle generation complete.
✔ Index html generation complete.

Initial Chunk Files                                                               | Names                                                                          |       Size
vendor.js                                                                         | vendor                                                                         |    7.68 MB
main.js                                                                           | main                                                                           |    1.04 MB
polyfills.js                                                                      | polyfills                                                                      |  149.58 kB
scripts.js                                                                        | scripts                                                                        |  145.17 kB
styles.css                                                                        | styles                                                                         |   19.92 kB
runtime.js                                                                        | runtime                                                                        |    9.57 kB

                                                                                  | Initial Total                                                                  |    9.04 MB

Lazy Chunk Files                                                                  | Names                                                                          |       Size
quiz-quiz-flow-quiz-flow-module.js                                                | quiz-quiz-flow-quiz-flow-module                                                |  599.44 kB
quiz-quiz-manager-quiz-manager-module.js                                          | quiz-quiz-manager-quiz-manager-module                                          |  501.79 kB
theme-blackbeauty-__CSS_FILE_HASH__.css                                           | theme-blackbeauty-__CSS_FILE_HASH__                                            |  187.52 kB
theme-Material-__CSS_FILE_HASH__.css                                              | theme-Material-__CSS_FILE_HASH__                                               |  187.00 kB
theme-default.css                                                                 | theme-default                                                                  |  186.99 kB
quiz-quiz-module.js                                                               | quiz-quiz-module                                                               |  165.93 kB
admin-admin-module.js                                                             | admin-admin-module                                                             |  122.45 kB
i18n-manager-i18n-manager-module.js                                               | i18n-manager-i18n-manager-module                                               |   64.03 kB
root-nickname-chooser-nickname-chooser-module.js                                  | root-nickname-chooser-nickname-chooser-module                                  |   52.37 kB
root-info-info-module.js                                                          | root-info-info-module                                                          |   36.33 kB
default~i18n-manager-i18n-manager-module~quiz-quiz-manager-quiz-manager-module.js | default~i18n-manager-i18n-manager-module~quiz-quiz-manager-quiz-manager-module |   27.86 kB
common.js                                                                         | common                                                                         | 1014 bytes

Build at: 2020-12-14T10:26:48.053Z - Hash: 7d600710b412a42b578f - Time: 136227ms

Warning: /net/vcac-ubuntu16/disc1/www/html/arsnova-clicks/arsnova-click-v2-frontend/node_modules/angular2-hotkeys/__ivy_ngcc__/fesm2015/angular2-hotkeys.js depends on 'mousetrap'. CommonJS or AM                                       D dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /net/vcac-ubuntu16/disc1/www/html/arsnova-clicks/arsnova-click-v2-frontend/node_modules/universal-cookie-consent/__ivy_ngcc__/fesm2015/universal-cookie-consent.js depends on 'js-cookie'                                       . CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Compiled successfully.
Error from chokidar (/net/vcac-ubuntu16/disc1/www/html/arsnova-clicks/arsnova-click-v2-frontend/src/assets/images/emojis): Error: ENOSPC: System limit for number of file watchers reached, watch                                        '/net/vcac-ubuntu16/disc1/www/html/arsnova-clicks/arsnova-click-v2-frontend/src/assets/images/emojis/purse.png'
Error from chokidar (/net/vcac-ubuntu16/disc1/www/html/arsnova-clicks/arsnova-click-v2-frontend/src/assets/images/emojis): 
...
other logs like these
...
[HPM] Error occurred while trying to proxy request /api/v1 from localhost:46079 to http://localhost:3010 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)

[HPM] Error occurred while trying to proxy request /api/v1/quiz/public/amount from localhost:46079 to http://localhost:3010 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)

[HPM] Error occurred while trying to proxy request /api/v1/quiz/public/amount/own from localhost:46079 to http://localhost:3010 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)

[HPM] Error occurred while trying to proxy request /api/v1/quiz/active from localhost:46079 to http://localhost:3010 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

In Chrome it does say that it can't connect to 'ws://localhost:15674/ws'.
![image](https://user-images.githubusercontent.com/3785570/102080650-1f919c00-3e0f-11eb-929a-f95c31356709.png)

Do u have any idea why I get these errors? I followed both installations guides.

**Comment by PhilippSautner97** [comment]
If you follow the guide, your containers should look something like this:  
![image](https://user-images.githubusercontent.com/60929505/102089186-2ffc4380-3e1c-11eb-8344-7c2c08f03560.png)  
The frontend tries to connect to the ports which don't exist since the incorrect containers have been loaded up. 
I have cleaned up some mistakes in the Installationguides, I would suggest you try to follow them again, but make sure to delete/shutdown your docker containers before doing so.

**Comment by SaifAlDilaimi** [comment]
Hey Philipp,

thanks for replying so quickly. I have deleted everything and reinstalled the frontend/backend again. 

The frontend shows now this:

```
root@vmits0454 /var/www/html/arsnova-clicks/arsnova-click-v2-frontend (staging *=) #  npm run dev:ssr

> arsnova-click-v2-frontend@2.0.0 dev:ssr /net/vcac-ubuntu16/disc1/www/html/arsnova-clicks/arsnova-click-v2-frontend
> ng run frontend:serve-ssr

****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
✔ Server application bundle generation complete.

Initial Chunk Files                                                               | Names                                                                          |      Size
main.js                                                                           | main                                                                           |  11.49 MB

                                                                                  | Initial Total                                                                  |  11.49 MB

Lazy Chunk Files                                                                  | Names                                                                          |      Size
quiz-quiz-flow-quiz-flow-module.js                                                | quiz-quiz-flow-quiz-flow-module                                                | 518.63 kB
quiz-quiz-manager-quiz-manager-module.js                                          | quiz-quiz-manager-quiz-manager-module                                          | 502.78 kB
quiz-quiz-module.js                                                               | quiz-quiz-module                                                               | 167.06 kB
admin-admin-module.js                                                             | admin-admin-module                                                             | 122.42 kB
vendors~quiz-quiz-flow-quiz-flow-module.js                                        | vendors~quiz-quiz-flow-quiz-flow-module                                        |  82.65 kB
i18n-manager-i18n-manager-module.js                                               | i18n-manager-i18n-manager-module                                               |  64.00 kB
root-nickname-chooser-nickname-chooser-module.js                                  | root-nickname-chooser-nickname-chooser-module                                  |  52.62 kB
root-info-info-module.js                                                          | root-info-info-module                                                          |  36.30 kB
vendors~i18n-manager-i18n-manager-module~quiz-quiz-manager-quiz-manager-module.js | vendors~i18n-manager-i18n-manager-module~quiz-quiz-manager-quiz-manager-module |  27.83 kB

Build at: 2020-12-14T14:33:55.655Z - Hash: 9fb67252775207dafeb2 - Time: 165434ms
✔ Browser application bundle generation complete.
✔ Index html generation complete.

Initial Chunk Files                                                               | Names                                                                          |       Size
vendor.js                                                                         | vendor                                                                         |    7.68 MB
main.js                                                                           | main                                                                           |    1.04 MB
polyfills.js                                                                      | polyfills                                                                      |  149.58 kB
scripts.js                                                                        | scripts                                                                        |  145.17 kB
styles.css                                                                        | styles                                                                         |   19.92 kB
runtime.js                                                                        | runtime                                                                        |    9.57 kB

                                                                                  | Initial Total                                                                  |    9.04 MB

Lazy Chunk Files                                                                  | Names                                                                          |       Size
quiz-quiz-flow-quiz-flow-module.js                                                | quiz-quiz-flow-quiz-flow-module                                                |  599.44 kB
quiz-quiz-manager-quiz-manager-module.js                                          | quiz-quiz-manager-quiz-manager-module                                          |  501.79 kB
theme-blackbeauty-__CSS_FILE_HASH__.css                                           | theme-blackbeauty-__CSS_FILE_HASH__                                            |  187.52 kB
theme-Material-__CSS_FILE_HASH__.css                                              | theme-Material-__CSS_FILE_HASH__                                               |  187.00 kB
theme-default.css                                                                 | theme-default                                                                  |  186.99 kB
quiz-quiz-module.js                                                               | quiz-quiz-module                                                               |  165.93 kB
admin-admin-module.js                                                             | admin-admin-module                                                             |  122.45 kB
i18n-manager-i18n-manager-module.js                                               | i18n-manager-i18n-manager-module                                               |   64.03 kB
root-nickname-chooser-nickname-chooser-module.js                                  | root-nickname-chooser-nickname-chooser-module                                  |   52.37 kB
root-info-info-module.js                                                          | root-info-info-module                                                          |   36.33 kB
default~i18n-manager-i18n-manager-module~quiz-quiz-manager-quiz-manager-module.js | default~i18n-manager-i18n-manager-module~quiz-quiz-manager-quiz-manager-module |   27.86 kB
common.js                                                                         | common                                                                         | 1014 bytes

Build at: 2020-12-14T14:34:30.089Z - Hash: 7d600710b412a42b578f - Time: 185274ms

Warning: /net/vcac-ubuntu16/disc1/www/html/arsnova-clicks/arsnova-click-v2-frontend/node_modules/angular2-hotkeys/__ivy_ngcc__/fesm2015/angular2-hotkeys.js depends on 'mousetrap'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: /net/vcac-ubuntu16/disc1/www/html/arsnova-clicks/arsnova-click-v2-frontend/node_modules/universal-cookie-consent/__ivy_ngcc__/fesm2015/universal-cookie-consent.js depends on 'js-cookie'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies



Compiled successfully.
[HPM] Proxy created: /api/v1  -> http://localhost:3010

[HPM] Proxy created: /api/lib  -> http://localhost:3010

** Angular Universal Live Development Server is listening on http://localhost:4200, open your browser on http://localhost:4200 **
switching to  fill-success

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s32x32.png

Rewriting static request https://arsnova.click/assets/meta/Material/linkNodes.json

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s32x32.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s64x64.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s72x72.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s76x76.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s114x114.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s120x120.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s128x128.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s144x144.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s152x152.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s180x180.png
Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s192x192.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s512x512.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s1024x1024.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s32x32.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s64x64.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s72x72.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s76x76.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s114x114.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s120x120.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s128x128.png
Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s144x144.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s152x152.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s180x180.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s192x192.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s512x512.png
Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s1024x1024.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s64x64.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s1024x1024.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s512x512.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s192x192.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s180x180.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s152x152.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s144x144.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s128x128.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s120x120.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s114x114.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s76x76.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s72x72.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s64x64.png

Rewriting static request https://arsnova.click/assets/images/theme/Material/logo_s32x32.png
```

The backend doesn't throw any errors now:
```
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15376,"level":30,"msg":"Listening on port 3010","time":"2020-12-14T14:29:48.618Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15432,"level":30,"msg":"AMQP Exchanges initialized","time":"2020-12-14T14:29:48.620Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15432,"level":30,"msg":"RabbitMQ connected","time":"2020-12-14T14:29:48.620Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15432,"level":30,"msg":"External services connected","time":"2020-12-14T14:29:48.620Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15370,"level":30,"msg":"MongoDB connected","time":"2020-12-14T14:29:48.657Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15426,"level":30,"msg":"[Worker 15426] started","time":"2020-12-14T14:29:48.677Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15370,"level":30,"msg":"AMQP Exchanges initialized","time":"2020-12-14T14:29:48.682Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15370,"level":30,"msg":"RabbitMQ connected","time":"2020-12-14T14:29:48.683Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15370,"level":30,"msg":"External services connected","time":"2020-12-14T14:29:48.683Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15426,"level":30,"msg":"Listening on port 3010","time":"2020-12-14T14:29:48.685Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15376,"level":30,"msg":"MongoDB connected","time":"2020-12-14T14:29:48.692Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15411,"level":30,"msg":"MongoDB connected","time":"2020-12-14T14:29:48.693Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15411,"level":30,"msg":"AMQP Exchanges initialized","time":"2020-12-14T14:29:48.701Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15411,"level":30,"msg":"RabbitMQ connected","time":"2020-12-14T14:29:48.702Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15411,"level":30,"msg":"External services connected","time":"2020-12-14T14:29:48.702Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15376,"level":30,"msg":"AMQP Exchanges initialized","time":"2020-12-14T14:29:48.723Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15376,"level":30,"msg":"RabbitMQ connected","time":"2020-12-14T14:29:48.723Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15376,"level":30,"msg":"External services connected","time":"2020-12-14T14:29:48.723Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15426,"level":30,"msg":"MongoDB connected","time":"2020-12-14T14:29:48.760Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15426,"level":30,"msg":"AMQP Exchanges initialized","time":"2020-12-14T14:29:48.791Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15426,"level":30,"msg":"RabbitMQ connected","time":"2020-12-14T14:29:48.791Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15426,"level":30,"msg":"External services connected","time":"2020-12-14T14:29:48.791Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15356,"level":30,"req":{"method":"GET","url":"/api/v1"},"res":{"statusCode":200},"msg":"","time":"2020-12-14T14:37:35.572Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15362,"level":30,"req":{"method":"GET","url":"/api/v1/quiz/public/amount"},"res":{"statusCode":200},"msg":"","time":"2020-12-14T14:37:35.711Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15446,"level":30,"req":{"method":"GET","url":"/api/v1/quiz/public/amount/own"},"res":{"statusCode":200},"msg":"","time":"2020-12-14T14:37:35.717Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15404,"level":30,"req":{"method":"GET","url":"/api/v1/quiz/active"},"res":{"statusCode":200},"msg":"","time":"2020-12-14T14:37:36.106Z","v":0}
{"name":"arsnova-click-v2-backend","hostname":"vmits0454","pid":15397,"level":30,"req":{"method":"OPTIONS","url":"/api/v1"},"res":{"statusCode":200},"msg":"","time":"2020-12-14T14:37:36.394Z","v":0}
```

However the webpage shows that it isn't connected:
![image](https://user-images.githubusercontent.com/3785570/102095842-4ad2b600-3e24-11eb-8823-3e572fff2f9d.png)

**Comment by PhilippSautner97** [comment]
Hi, 

this Error is likely caused by not sourcing the `export-arsnova-click.env` file correctly or not restarting the docker containers in the backend.
